import { exec } from 'node:child_process';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { rimraf } from 'rimraf';

import { registry } from '../registry/index';

// Note: this script used to also write public/llms.txt and
// public/llms-full.txt from the component registry. Those static files
// shadowed the real route handlers in app/(llms)/ and shipped template
// content about UI components instead of the portfolio, so they are gone.

async function buildRegistryIndex() {
  let index = `/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {`;
  for (const item of registry.items) {
    const resolveFiles = item.files?.map((file) => `registry/${file.path}`);
    if (!resolveFiles) {
      continue;
    }

    const componentPath = item.files?.[0]?.path
      ? `@/registry/${item.files[0].path}`
      : '';

    index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ''}",
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
    files: [${item.files?.map((file) => {
      const filePath = `registry/${typeof file === 'string' ? file : file.path}`;
      const resolvedFilePath = path.resolve(filePath);
      return typeof file === 'string'
        ? `"${resolvedFilePath}"`
        : `{
      path: "${filePath}",
      type: "${file.type}",
      target: "${file.target ?? ''}"
    }`;
    })}],
    component: ${
      componentPath
        ? `React.lazy(async () => {
      const mod = await import("${componentPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    })`
        : 'null'
    },
    meta: ${JSON.stringify(item.meta)},
  },`;
  }

  index += `
  }`;

  // Write style index.
  rimraf.sync(path.join(process.cwd(), 'registry/__index__.tsx'));
  await fs.writeFile(path.join(process.cwd(), 'registry/__index__.tsx'), index);
}

async function buildRegistryJsonFile() {
  // 1. Fix the path for registry items.
  const fixedRegistry = {
    ...registry,
    items: registry.items.map((item) => {
      const files = item.files?.map((file) => {
        return {
          ...file,
          path: `registry/${file.path}`,
        };
      });

      return {
        ...item,
        files,
      };
    }),
  };

  // 2. Write the content of the registry to `registry.json`
  rimraf.sync(path.join(process.cwd(), `registry.json`));
  await fs.writeFile(
    path.join(process.cwd(), `registry.json`),
    JSON.stringify(fixedRegistry, null, 2)
  );

  // 3. Copy the registry.json to the public/r directory.
  await fs.cp(
    path.join(process.cwd(), 'registry.json'),
    path.join(process.cwd(), './public/r/registry.json'),
    { recursive: true }
  );

  // 3. Copy the registry.json to the public/r directory.
  await fs.cp(
    path.join(process.cwd(), 'registry.json'),
    path.join(process.cwd(), './public/registry.json'),
    { recursive: true }
  );
}

async function buildRegistry() {
  return new Promise((resolve, reject) => {
    const process = exec(`pnpm shadcn:build`);

    process.on('exit', (code) => {
      if (code === 0) {
        resolve(undefined);
      } else {
        reject(new Error(`Process exited with code ${code}`));
      }
    });
  });
}

try {
  console.log('🗂️ Building registry/__index__.tsx...');
  await buildRegistryIndex();
  console.log('✅ Registry index built successfully');

  console.log('💅 Building registry.json...');
  await buildRegistryJsonFile();
  console.log('✅ Registry JSON file built successfully');

  console.log('🏗️ Building registry...');
  await buildRegistry();
  console.log('✅ Registry build completed');
} catch (error) {
  console.error('❌ Build failed with error:');
  console.error(error);
  if (error instanceof Error) {
    console.error('Error stack:', error.stack);
  }
  process.exit(1);
}
